# Generated by Django 4.2.4 on 2023-09-05 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('total_distance', models.IntegerField(blank=True, default=0, null=True)),
                ('total_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabmanagement.booking')),
                ('cab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabmanagement.cab')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabmanagement.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabmanagement.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=1, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('cab_service', models.ManyToManyField(to='cabmanagement.cab')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripmanagement.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
