# Generated by Django 4.2.4 on 2023-09-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabmanagement', '0003_userinfo_remove_customer_user_remove_driver_user_and_more'),
        ('tripmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_info', to='cabmanagement.userinfo'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_info', to='cabmanagement.userinfo'),
        ),
    ]
