# Generated by Django 4.2.4 on 2023-09-15 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabmanagement', '0003_userinfo_remove_customer_user_remove_driver_user_and_more'),
        ('tripmanagement', '0002_alter_trip_customer_alter_trip_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_alter_userauthentication_mobile_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_authentication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userauthentication'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabmanagement.userinfo'),
        ),
        migrations.AddField(
            model_name='cab',
            name='driver_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabmanagement.userinfo'),
        ),
    ]
