# Generated by Django 4.2.4 on 2023-09-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabmanagement', '0004_delete_customer_delete_driver_userinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
