# Generated by Django 4.2.4 on 2023-09-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
